spring.application.name=account-service

spring.datasource.url=jdbc:postgresql://localhost:5433/account_db
spring.datasource.username=banking
spring.datasource.password=${DB_PASSWORD:banking}
spring.jpa.hibernate.ddl-auto=validate