spring.application.name=account-service

spring.datasource.url=jdbc:postgresql://localhost:5433/account_hexagonal_db
spring.datasource.username=banking
spring.datasource.password=${DB_PASSWORD:banking}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Logs
logging.file.name=logs/account-service.log

management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces

# Azure Service Bus
spring.cloud.azure.servicebus.namespace=sb-banking-hexagonal-dev
spring.cloud.azure.servicebus.entity-type=queue